project:
  type: website
  output-dir: docs

website:
  title: "Computer vision, biostatistics, and AI in Radiology"
  favicon: favicon.png
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ml-w
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=JNKeB6cAAAAJ&hl=en
      - icon: person-circle
        href: http://www.diir.cuhk.edu.hk/profile/mr-wong-lun-matthew
  page-navigation: true
  page-footer: "©Copyright 2024, MLun Wong"
  sidebar:
    contents: auto
    style: "floating"
    border: false
    background: none

format:
  html:
    theme: 
      dark: [quartz, styles.scss, dark-styles.scss]
      light: [quartz, styles.scss, light-styles.scss]
    css: 
      styles.css
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Georgia:wght@400;700&display=swap" rel="stylesheet">
    include-in-header:
      - file: assets/script_header.html
    highlight-style: ayu
    fig-align: center
    # html-math-method: katex
    # grid:
    #   sidebar-width: 0px
editor: visual

execute:
  freeze: auto