project:
  type: website
  output-dir: docs

website:
  title: "Computer vision, biostatistics, and AI in Radiology"
  favicon: favicon.png
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ml-w
      - icon: mortarboard
        text: Google Scholar
        href: https://scholar.google.com/citations?user=JNKeB6cAAAAJ&hl=en
      - icon: person-circle
        text: Academic Page
        href: http://www.diir.cuhk.edu.hk/profile/mr-wong-lun-matthew
format:
  html:
    theme: 
      dark: [quartz, styles.scss, dark-styles.scss]
      light: [quartz, styles.scss, light-styles.scss]
    css: 
      styles.css
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    include-in-header:
      - file: assets/script_header.html
    mainfont: Roboto
    highlight-style: ayu
  
    # html-math-method: katex

editor: visual

execute:
  freeze: auto